---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pfsense-lab-nedkoff-com-v1beta1-dnsresolverhostoverride
  failurePolicy: Fail
  name: mdnsresolverhostoverride-v1beta1.kb.io
  rules:
  - apiGroups:
    - pfsense.lab.nedkoff.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsresolverhostoverrides
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pfsense-lab-nedkoff-com-v1beta1-dnsresolverhostoverride
  failurePolicy: Fail
  name: vdnsresolverhostoverride-v1beta1.kb.io
  rules:
  - apiGroups:
    - pfsense.lab.nedkoff.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsresolverhostoverrides
  sideEffects: None
