---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pfsense.lab.nedkoff.com
  resources:
  - dnsresolverhostoverrides
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pfsense.lab.nedkoff.com
  resources:
  - dnsresolverhostoverrides/finalizers
  verbs:
  - update
- apiGroups:
  - pfsense.lab.nedkoff.com
  resources:
  - dnsresolverhostoverrides/status
  verbs:
  - get
  - patch
  - update
