//go:build !ignore_autogenerated

/*
Copyright 2025 Vess Nedkov.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverHostOverride) DeepCopyInto(out *DNSResolverHostOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverHostOverride.
func (in *DNSResolverHostOverride) DeepCopy() *DNSResolverHostOverride {
	if in == nil {
		return nil
	}
	out := new(DNSResolverHostOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSResolverHostOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverHostOverrideList) DeepCopyInto(out *DNSResolverHostOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSResolverHostOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverHostOverrideList.
func (in *DNSResolverHostOverrideList) DeepCopy() *DNSResolverHostOverrideList {
	if in == nil {
		return nil
	}
	out := new(DNSResolverHostOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSResolverHostOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverHostOverrideSpec) DeepCopyInto(out *DNSResolverHostOverrideSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverHostOverrideSpec.
func (in *DNSResolverHostOverrideSpec) DeepCopy() *DNSResolverHostOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(DNSResolverHostOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolverHostOverrideStatus) DeepCopyInto(out *DNSResolverHostOverrideStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolverHostOverrideStatus.
func (in *DNSResolverHostOverrideStatus) DeepCopy() *DNSResolverHostOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(DNSResolverHostOverrideStatus)
	in.DeepCopyInto(out)
	return out
}
